### ISSUE TITLE
Create note listing page UI

### ISSUE THREAD

**Issue by adil62** [adil62/neetoui-challenge#1]

**Comment by yedhink** [comment]
@adil62 Why are you assigning me this issue when you are the one who is supposed to fix the issue? Do you need any inputs from my end?

I believe the following doc is very precise and on point. It only talks about assigning PRs. But if you feel something needs to be added in the doc so as to avoid unnecessary assignments like you have done right now, then lemme know:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/31244999/191257892-9543902c-3b3b-408a-a03e-5cf3882bb8d6.png">

PS: I will review the PR only once the PR is assigned to me.

**Comment by adil62** [comment]
Docs are very clear. I assigned it to u by mistake.
